{ ... }:

{
  security.pki.certificates = [
    ''
      Alisa Lab Root CA 2026 EC
      -----BEGIN CERTIFICATE-----
      MIICLDCCAbKgAwIBAgIUPx4IfrUJ+Y9mEMydWkXlPIP22+kwCgYIKoZIzj0EAwMw
      RTELMAkGA1UEBhMCSlAxEjAQBgNVBAoMCUFsaXNhIExhYjEiMCAGA1UEAwwZQWxp
      c2EgTGFiIFJvb3QgQ0EgMjAyNiBFQzAeFw0yNjA1MTUwNzIxMjBaFw00NjA1MTAw
      NzIxMjBaMEUxCzAJBgNVBAYTAkpQMRIwEAYDVQQKDAlBbGlzYSBMYWIxIjAgBgNV
      BAMMGUFsaXNhIExhYiBSb290IENBIDIwMjYgRUMwdjAQBgcqhkjOPQIBBgUrgQQA
      IgNiAARdzy03M3GiV8DFvNHU3avVhJPLGpEA4L5Pk9WSurCYtPNQqBMKGuNRb62Z
      VEqnQgQtEHOPLmM/0mGRLfzHirLPh8v1+BJ4iM6ZHO4t1VAuoUil7pWfEb9Pv2JN
      dVY6nEejYzBhMB8GA1UdIwQYMBaAFLaWhMX7v3FpJXvYMCFEu3m1PtLzMA8GA1Ud
      EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQWBBS2loTF+79xaSV7
      2DAhRLt5tT7S8zAKBggqhkjOPQQDAwNoADBlAjB1f+UQRdU+fDV7484kYbCXQVhh
      TpMhGbBq7BZlULpt360zjoTmlr6u+ZOsiLpVHzICMQD4b49QVeEUe9Xv6ec6lVa+
      f1lcj+caSfcbN+7VBSiFcJndzhq/0qsXRwFwx0p1Ae0=
      -----END CERTIFICATE-----
    ''
  ];
}
